baseurl = "/"
title = "Global Women in Data Science Conference"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "Describe your website"
  sidebarAbout = [
    "The Global Women in Data Science (WiDS) Conference aims to inspire and educate data scientists worldwide, regardless of gender, and support women in the field. This annual one-day technical conference provides an opportunity to hear about the latest data science related research and applications in a broad set of domains, All genders are invited to participate in the conference, which features outstanding women doing outstanding work."
  ]


  # Nav links in the side bar
  [[params.navlinks]]
  name = "About"
  url = "event/"
  home = true

  [[params.navlinks]]
  name = "Schedule"
  url = "event/2_schedule"

  [[params.navlinks]]
  name = "Register"
  url = "https://goo.gl/forms/oR3u2z9OMdRKj7uo2"  


  [[params.navlinks]]
  name = "Career panel"
  url = "event/6_panel"  

  [[params.navlinks]]
  name = "WiDS Conference Website"
  url = "https://www.widsconference.org/"  
  

  [params.social]
  email = "datascience@csuchico.edu"
  
